### ISSUE TITLE
Upgrade to v3.0.0

### ISSUE THREAD

**Issue by joie96** [chatziko/wyoming-porcupine#1]
Hi, is there any way that you upgrade your implementation to porcupine v3.0.0?

Best regards,
joie96

**Comment by chatziko** [comment]
I did, although in my system I reached the 3 device limit, and I'm not sure whether in this version you can still restart/upgrade the addon without increasing the counter.

To be honest, I'm not getting that great accuracy and the montly limit is just annoying, so I'm not sure for how long I'll be using this..

**Comment by joie96** [comment]
Thank you very much anyways. I'm on the same boat. When I've got some time I'll compare porcupine against openwakeword. Do you have any experience compared to openwakeword?

**Comment by chatziko** [comment]
My limit was reset and I managed to do a bit of testing, v3 seems to work. So closing this as completed.
