### ISSUE TITLE
 Picovoice Error (code `00000136`)

### ISSUE THREAD

**Issue by emanuelbaltaretu** [chatziko/wyoming-porcupine#2]
Hi, I have the following error:

DEBUG:root:Namespace(uri='tcp://0.0.0.0:10401', data_dir=PosixPath('/usr/src/.venv/lib/python3.11/site-packages/wyoming_porcupine/data'), system='linux', sensitivity=0.5, access_key='****censored****', custom_keyword_dir=['/custom'], debug=True)
 

 INFO:root:Ready
 

 DEBUG:root:Client connected: 135089827551418
 

 DEBUG:root:Loading Carlos for es
 

 DEBUG:root:Client disconnected: 135089827551418
 

 ERROR:asyncio:Task exception was never retrieved
 

 future: <Task finished name='Task-5' coro=<AsyncEventHandler.run() done, defined at /usr/src/.venv/lib/python3.11/site-packages/wyoming/server.py:28> exception=PorcupineInvalidArgumentError('Initialization failed')>
 

 Traceback (most recent call last):
 

   File "/usr/src/.venv/lib/python3.11/site-packages/wyoming/server.py", line 35, in run
 

     if not (await self.handle_event(event)):
 

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 

   File "/usr/src/.venv/lib/python3.11/site-packages/wyoming_porcupine/__main__.py", line 236, in handle_event
 

     await self._load_keyword(detect.names[0])
 

   File "/usr/src/.venv/lib/python3.11/site-packages/wyoming_porcupine/__main__.py", line 298, in _load_keyword
 

     self.detector = await self.state.get_porcupine(
 

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 

   File "/usr/src/.venv/lib/python3.11/site-packages/wyoming_porcupine/__main__.py", line 79, in get_porcupine
 

     porcupine = pvporcupine.create(
 

                 ^^^^^^^^^^^^^^^^^^^
 

   File "/usr/src/.venv/lib/python3.11/site-packages/pvporcupine/_factory.py", line 69, in create
 

     return Porcupine(
 

            ^^^^^^^^^^
 

   File "/usr/src/.venv/lib/python3.11/site-packages/pvporcupine/_porcupine.py", line 198, in __init__
 

     raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
 

 pvporcupine._porcupine.PorcupineInvalidArgumentError: Initialization failed:
 

   [0] Keyword file (.ppn) file has incorrect format or belongs to a different platform.
 

   [1] Picovoice Error (code `00000136`)
 

   [2] Loading keyword file at `/custom/Carlos_es_linux_v3_0_0.ppn` failed with `INVALID_ARGUMENT`.
   
   
 I am running this into a container if it makes any difference. Also if i remove       - "--wake-word-name"  - "Carlos" the default Porcupine wake word works fine

**Comment by chatziko** [comment]
No idea, maybe the .ppn file is not accessible inside the container?

Also is your platform really "linux?

**Comment by emanuelbaltaretu** [comment]
So it sees the file from the container, you can see it in the logs, " /custom/Carlos_es_linux_v3_0_0.ppn" and platform is linux, it's on a headless debian intel nuc, not rasp pi. 

I tried downloading their ppn for linux from the demo repo like computer and they did work as well.

Unfortunately I just realised having it in a container is futile because of the device limitation and I already reached the monthly limit while trying to fix it. 

I will close the issue as unless i make a new account we will be unable to test a fix for it.

Thanks for taking from your time, have a great weekend

**Comment by emanuelbaltaretu** [comment]
Closing

**Comment by chatziko** [comment]
When running in a container make sure your `HOME` dir is preserved across restarts (use a volume, bind, etc) to avoid increasing the count each time. In the addon version I set `HOME=/data` cause the `/data` dir is preserved.

**Comment by emanuelbaltaretu** [comment]
Thanks for the tip, i will give it a try when when i will be able again, i will keep the current open wake word implementation in the meantime that it's kinda hit or miss, and maybe sometime in the future i will get a dedicated rpi for this whole satellite setup as it's a pain the butt currently with containers
